//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronCow.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronCow.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string AboutLower {
            get {
                return ResourceManager.GetString("AboutLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Milkman.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about milkman.
        /// </summary>
        internal static string AboutMenuLower {
            get {
                return ResourceManager.GetString("AboutMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT MILKMAN.
        /// </summary>
        internal static string AboutMenuUpper {
            get {
                return ResourceManager.GetString("AboutMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string AboutUpper {
            get {
                return ResourceManager.GetString("AboutUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding note....
        /// </summary>
        internal static string AddingNote {
            get {
                return ResourceManager.GetString("AddingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding task....
        /// </summary>
        internal static string AddingTask {
            get {
                return ResourceManager.GetString("AddingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string AddMenuLower {
            get {
                return ResourceManager.GetString("AddMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string AddMenuUpper {
            get {
                return ResourceManager.GetString("AddMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add note.
        /// </summary>
        internal static string AddNoteLower {
            get {
                return ResourceManager.GetString("AddNoteLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NOTE.
        /// </summary>
        internal static string AddNoteUpper {
            get {
                return ResourceManager.GetString("AddNoteUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Smart Add dialog for adding tasks.
        /// </summary>
        internal static string AddTaskDialogSetting {
            get {
                return ResourceManager.GetString("AddTaskDialogSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string AddTaskDialogTitle {
            get {
                return ResourceManager.GetString("AddTaskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        internal static string AddTaskLower {
            get {
                return ResourceManager.GetString("AddTaskLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TASK.
        /// </summary>
        internal static string AddTaskUpper {
            get {
                return ResourceManager.GetString("AddTaskUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string AllLower {
            get {
                return ResourceManager.GetString("AllLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tasks.
        /// </summary>
        internal static string AllTasks {
            get {
                return ResourceManager.GetString("AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all tasks.
        /// </summary>
        internal static string AllTasksLower {
            get {
                return ResourceManager.GetString("AllTasksLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL TASKS.
        /// </summary>
        internal static string AllTasksUpper {
            get {
                return ResourceManager.GetString("AllTasksUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string AllUpper {
            get {
                return ResourceManager.GetString("AllUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman needs permission to use your Remember The Milk account to continue. Sign in to your account and tap the Complete button to continue.
        ///
        ///Milkman will never store or share your personal information..
        /// </summary>
        internal static string AuthorizationDialog {
            get {
                return ResourceManager.GetString("AuthorizationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string AuthorizationDialogTitle {
            get {
                return ResourceManager.GetString("AuthorizationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization.
        /// </summary>
        internal static string AuthorizationLower {
            get {
                return ResourceManager.GetString("AuthorizationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION.
        /// </summary>
        internal static string AuthorizationUpper {
            get {
                return ResourceManager.GetString("AuthorizationUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        internal static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync data automatically.
        /// </summary>
        internal static string AutomaticSyncSetting {
            get {
                return ResourceManager.GetString("AutomaticSyncSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        internal static string BodyLower {
            get {
                return ResourceManager.GetString("BodyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY.
        /// </summary>
        internal static string BodyUpper {
            get {
                return ResourceManager.GetString("BodyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelMenu {
            get {
                return ResourceManager.GetString("CancelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string CancelMenuLower {
            get {
                return ResourceManager.GetString("CancelMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CancelMenuUpper {
            get {
                return ResourceManager.GetString("CancelMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this task as complete?.
        /// </summary>
        internal static string CompleteDialog {
            get {
                return ResourceManager.GetString("CompleteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string CompleteDialogTitle {
            get {
                return ResourceManager.GetString("CompleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string CompleteMenu {
            get {
                return ResourceManager.GetString("CompleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string CompleteMenuLower {
            get {
                return ResourceManager.GetString("CompleteMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE.
        /// </summary>
        internal static string CompleteMenuUpper {
            get {
                return ResourceManager.GetString("CompleteMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark the selected tasks as complete?.
        /// </summary>
        internal static string CompleteTaskPluralDialog {
            get {
                return ResourceManager.GetString("CompleteTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark the selected task as complete?.
        /// </summary>
        internal static string CompleteTaskSingleDialog {
            get {
                return ResourceManager.GetString("CompleteTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing task....
        /// </summary>
        internal static string CompletingTask {
            get {
                return ResourceManager.GetString("CompletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing tasks....
        /// </summary>
        internal static string CompletingTasks {
            get {
                return ResourceManager.GetString("CompletingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        internal static string DashboardLower {
            get {
                return ResourceManager.GetString("DashboardLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardMenu {
            get {
                return ResourceManager.GetString("DashboardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        internal static string DashboardMenuLower {
            get {
                return ResourceManager.GetString("DashboardMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string DashboardMenuUpper {
            get {
                return ResourceManager.GetString("DashboardMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string DashboardUpper {
            get {
                return ResourceManager.GetString("DashboardUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        internal static string DateLower {
            get {
                return ResourceManager.GetString("DateLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date &amp; time.
        /// </summary>
        internal static string DateTimeLower {
            get {
                return ResourceManager.GetString("DateTimeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE &amp; TIME.
        /// </summary>
        internal static string DateTimeUpper {
            get {
                return ResourceManager.GetString("DateTimeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string DateUpper {
            get {
                return ResourceManager.GetString("DateUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string DeleteMenuLower {
            get {
                return ResourceManager.GetString("DeleteMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string DeleteMenuUpper {
            get {
                return ResourceManager.GetString("DeleteMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this note?.
        /// </summary>
        internal static string DeleteNoteDialog {
            get {
                return ResourceManager.GetString("DeleteNoteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteNoteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteNoteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        internal static string DeleteTaskDialog {
            get {
                return ResourceManager.GetString("DeleteTaskDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTaskDialogTitle {
            get {
                return ResourceManager.GetString("DeleteTaskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tasks?.
        /// </summary>
        internal static string DeleteTaskPluralDialog {
            get {
                return ResourceManager.GetString("DeleteTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected task?.
        /// </summary>
        internal static string DeleteTaskSingleDialog {
            get {
                return ResourceManager.GetString("DeleteTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting note....
        /// </summary>
        internal static string DeletingNote {
            get {
                return ResourceManager.GetString("DeletingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting task....
        /// </summary>
        internal static string DeletingTask {
            get {
                return ResourceManager.GetString("DeletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting tasks....
        /// </summary>
        internal static string DeletingTasks {
            get {
                return ResourceManager.GetString("DeletingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string DetailsLower {
            get {
                return ResourceManager.GetString("DetailsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        internal static string DetailsUpper {
            get {
                return ResourceManager.GetString("DetailsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your donation! Your support motivates me to keep developing for Milkman, the best Remember The Milk client for Windows Phone..
        /// </summary>
        internal static string DonateDialog {
            get {
                return ResourceManager.GetString("DonateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string DonateDialogTitle {
            get {
                return ResourceManager.GetString("DonateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string DonateMenu {
            get {
                return ResourceManager.GetString("DonateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        internal static string DonateMenuLower {
            get {
                return ResourceManager.GetString("DonateMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        internal static string DonateMenuUpper {
            get {
                return ResourceManager.GetString("DonateMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string DueAt {
            get {
                return ResourceManager.GetString("DueAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string EditMenuLower {
            get {
                return ResourceManager.GetString("EditMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string EditMenuUpper {
            get {
                return ResourceManager.GetString("EditMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit note.
        /// </summary>
        internal static string EditNoteLower {
            get {
                return ResourceManager.GetString("EditNoteLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT NOTE.
        /// </summary>
        internal static string EditNoteUpper {
            get {
                return ResourceManager.GetString("EditNoteUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit task.
        /// </summary>
        internal static string EditTaskLower {
            get {
                return ResourceManager.GetString("EditTaskLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT TASK.
        /// </summary>
        internal static string EditTaskUpper {
            get {
                return ResourceManager.GetString("EditTaskUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no lists to display..
        /// </summary>
        internal static string EmptyDashboardLists {
            get {
                return ResourceManager.GetString("EmptyDashboardLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no tags to display..
        /// </summary>
        internal static string EmptyDashboardTags {
            get {
                return ResourceManager.GetString("EmptyDashboardTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tasks nearby. Woohoo!.
        /// </summary>
        internal static string EmptyNearbyTaskList {
            get {
                return ResourceManager.GetString("EmptyNearbyTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notes for this task..
        /// </summary>
        internal static string EmptyNotes {
            get {
                return ResourceManager.GetString("EmptyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no incomplete tasks in this list. Woohoo!.
        /// </summary>
        internal static string EmptyTaskList {
            get {
                return ResourceManager.GetString("EmptyTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string FeedbackMenu {
            get {
                return ResourceManager.GetString("FeedbackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        internal static string FeedbackMenuLower {
            get {
                return ResourceManager.GetString("FeedbackMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        internal static string FeedbackMenuUpper {
            get {
                return ResourceManager.GetString("FeedbackMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        internal static string HubTileEmpty {
            get {
                return ResourceManager.GetString("HubTileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        internal static string HubTilePlural {
            get {
                return ResourceManager.GetString("HubTilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string HubTileSingle {
            get {
                return ResourceManager.GetString("HubTileSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore priority when sorting tasks.
        /// </summary>
        internal static string IgnorePrioritySetting {
            get {
                return ResourceManager.GetString("IgnorePrioritySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a moment....
        /// </summary>
        internal static string JustAMoment {
            get {
                return ResourceManager.GetString("JustAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        internal static string ListsLower {
            get {
                return ResourceManager.GetString("ListsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTS.
        /// </summary>
        internal static string ListUpper {
            get {
                return ResourceManager.GetString("ListUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show number of tasks on Live Tile counter.
        /// </summary>
        internal static string LiveTileCounterSetting {
            get {
                return ResourceManager.GetString("LiveTileCounterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due today and overdue.
        /// </summary>
        internal static string LiveTileCounterSetting1 {
            get {
                return ResourceManager.GetString("LiveTileCounterSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        internal static string LiveTileCounterSetting2 {
            get {
                return ResourceManager.GetString("LiveTileCounterSetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due today.
        /// </summary>
        internal static string LiveTileDueToday {
            get {
                return ResourceManager.GetString("LiveTileDueToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more due today.
        /// </summary>
        internal static string LiveTileMoreDueToday {
            get {
                return ResourceManager.GetString("LiveTileMoreDueToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more nearby.
        /// </summary>
        internal static string LiveTileMoreNearby {
            get {
                return ResourceManager.GetString("LiveTileMoreNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more overdue.
        /// </summary>
        internal static string LiveTileMoreOverdue {
            get {
                return ResourceManager.GetString("LiveTileMoreOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        internal static string LiveTileNearby {
            get {
                return ResourceManager.GetString("LiveTileNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string LiveTileOverdue {
            get {
                return ResourceManager.GetString("LiveTileOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when tasks are nearby.
        /// </summary>
        internal static string LocationRemindersSetting {
            get {
                return ResourceManager.GetString("LocationRemindersSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been a few days since you downloaded Milkman. Would you like to leave a review for it on the Windows Phone Store?.
        /// </summary>
        internal static string MarketplaceDialog {
            get {
                return ResourceManager.GetString("MarketplaceDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Milkman.
        /// </summary>
        internal static string MarketplaceDialogTitle {
            get {
                return ResourceManager.GetString("MarketplaceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman.
        /// </summary>
        internal static string Milkman {
            get {
                return ResourceManager.GetString("Milkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milkman.
        /// </summary>
        internal static string MilkmanLower {
            get {
                return ResourceManager.GetString("MilkmanLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILKMAN.
        /// </summary>
        internal static string MilkmanUpper {
            get {
                return ResourceManager.GetString("MilkmanUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        internal static string Nearby {
            get {
                return ResourceManager.GetString("Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        internal static string NearbyLower {
            get {
                return ResourceManager.GetString("NearbyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby location radius.
        /// </summary>
        internal static string NearbyRadiusSetting {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 mile.
        /// </summary>
        internal static string NearbyRadiusSetting1 {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 miles.
        /// </summary>
        internal static string NearbyRadiusSetting2 {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 miles.
        /// </summary>
        internal static string NearbyRadiusSetting3 {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 miles.
        /// </summary>
        internal static string NearbyRadiusSetting4 {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 miles.
        /// </summary>
        internal static string NearbyRadiusSetting5 {
            get {
                return ResourceManager.GetString("NearbyRadiusSetting5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEARBY.
        /// </summary>
        internal static string NearbyUpper {
            get {
                return ResourceManager.GetString("NearbyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when trying to contact the Remember The Milk servers. Are you connected to the network?.
        /// </summary>
        internal static string NetworkConnectionDialog {
            get {
                return ResourceManager.GetString("NetworkConnectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Contacting Server.
        /// </summary>
        internal static string NetworkConnectionDialogTitle {
            get {
                return ResourceManager.GetString("NetworkConnectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        internal static string NeverLower {
            get {
                return ResourceManager.GetString("NeverLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEVER.
        /// </summary>
        internal static string NeverUpper {
            get {
                return ResourceManager.GetString("NeverUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No due date.
        /// </summary>
        internal static string NoDueDate {
            get {
                return ResourceManager.GetString("NoDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string NoLower {
            get {
                return ResourceManager.GetString("NoLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string NoneLower {
            get {
                return ResourceManager.GetString("NoneLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string NoneUpper {
            get {
                return ResourceManager.GetString("NoneUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        internal static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        internal static string NotesLower {
            get {
                return ResourceManager.GetString("NotesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        internal static string NotesUpper {
            get {
                return ResourceManager.GetString("NotesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently do not have an active network connection available. Would you like to switch to offline mode for this session?.
        /// </summary>
        internal static string OfflineConnectionDialog {
            get {
                return ResourceManager.GetString("OfflineConnectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connection Unavailable.
        /// </summary>
        internal static string OfflineConnectionDialogTitle {
            get {
                return ResourceManager.GetString("OfflineConnectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over an hour ago.
        /// </summary>
        internal static string OverAnHourAgo {
            get {
                return ResourceManager.GetString("OverAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        internal static string OverdueLower {
            get {
                return ResourceManager.GetString("OverdueLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERDUE.
        /// </summary>
        internal static string OverdueUpper {
            get {
                return ResourceManager.GetString("OverdueUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages task reminders, location notifications, and live tile updates..
        /// </summary>
        internal static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        internal static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is already pinned to your start screen. If you need to replace it, remove the tile from your start screen and then reopen Milkman..
        /// </summary>
        internal static string PinToStartDialog {
            get {
                return ResourceManager.GetString("PinToStartDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin To Start.
        /// </summary>
        internal static string PinToStartDialogTitle {
            get {
                return ResourceManager.GetString("PinToStartDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        internal static string PinToStartLower {
            get {
                return ResourceManager.GetString("PinToStartLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN TO START.
        /// </summary>
        internal static string PinToStartUpper {
            get {
                return ResourceManager.GetString("PinToStartUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponed.
        /// </summary>
        internal static string Postponed {
            get {
                return ResourceManager.GetString("Postponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone this task?.
        /// </summary>
        internal static string PostponeDialog {
            get {
                return ResourceManager.GetString("PostponeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        internal static string PostponeDialogTitle {
            get {
                return ResourceManager.GetString("PostponeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        internal static string PostponeMenu {
            get {
                return ResourceManager.GetString("PostponeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postpone.
        /// </summary>
        internal static string PostponeMenuLower {
            get {
                return ResourceManager.GetString("PostponeMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTPONE.
        /// </summary>
        internal static string PostponeMenuUpper {
            get {
                return ResourceManager.GetString("PostponeMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone the selected tasks?.
        /// </summary>
        internal static string PostponeTaskPluralDialog {
            get {
                return ResourceManager.GetString("PostponeTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone the selected task?.
        /// </summary>
        internal static string PostponeTaskSingleDialog {
            get {
                return ResourceManager.GetString("PostponeTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponing task....
        /// </summary>
        internal static string PostponingTask {
            get {
                return ResourceManager.GetString("PostponingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponing tasks....
        /// </summary>
        internal static string PostponingTasks {
            get {
                return ResourceManager.GetString("PostponingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string RegisterLower {
            get {
                return ResourceManager.GetString("RegisterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        internal static string RegisterUpper {
            get {
                return ResourceManager.GetString("RegisterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman requires a Remember The Milk account to sync your tasks to the web and across all of your devices. Create an account and return to Milkman to continue.
        ///
        ///Milkman will never store or share your personal information..
        /// </summary>
        internal static string RegistrationDialog {
            get {
                return ResourceManager.GetString("RegistrationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationDialogTitle {
            get {
                return ResourceManager.GetString("RegistrationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryMenu {
            get {
                return ResourceManager.GetString("RetryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        internal static string RetryMenuLower {
            get {
                return ResourceManager.GetString("RetryMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETRY.
        /// </summary>
        internal static string RetryMenuUpper {
            get {
                return ResourceManager.GetString("RetryMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string SaveMenuLower {
            get {
                return ResourceManager.GetString("SaveMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string SaveMenuUpper {
            get {
                return ResourceManager.GetString("SaveMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving note....
        /// </summary>
        internal static string SavingNote {
            get {
                return ResourceManager.GetString("SavingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving task....
        /// </summary>
        internal static string SavingTask {
            get {
                return ResourceManager.GetString("SavingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectMenu {
            get {
                return ResourceManager.GetString("SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string SelectMenuLower {
            get {
                return ResourceManager.GetString("SelectMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string SelectMenuUpper {
            get {
                return ResourceManager.GetString("SelectMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while loading your settings. You may want to reload this page to ensure that your settings are loaded correctly..
        /// </summary>
        internal static string SettingsErrorDialog {
            get {
                return ResourceManager.GetString("SettingsErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SettingsErrorDialogTitle {
            get {
                return ResourceManager.GetString("SettingsErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string SettingsLower {
            get {
                return ResourceManager.GetString("SettingsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string SettingsMenuLower {
            get {
                return ResourceManager.GetString("SettingsMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SettingsMenuUpper {
            get {
                return ResourceManager.GetString("SettingsMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SettingsUpper {
            get {
                return ResourceManager.GetString("SettingsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        internal static string SignInLower {
            get {
                return ResourceManager.GetString("SignInLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInUpper {
            get {
                return ResourceManager.GetString("SignInUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out of Milkman and remove all of your data?.
        /// </summary>
        internal static string SignOutDialog {
            get {
                return ResourceManager.GetString("SignOutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutDialogTitle {
            get {
                return ResourceManager.GetString("SignOutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutMenu {
            get {
                return ResourceManager.GetString("SignOutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        internal static string SignOutMenuLower {
            get {
                return ResourceManager.GetString("SignOutMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        internal static string SignOutMenuUpper {
            get {
                return ResourceManager.GetString("SignOutMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing tasks....
        /// </summary>
        internal static string SyncingTasks {
            get {
                return ResourceManager.GetString("SyncingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string SyncMenu {
            get {
                return ResourceManager.GetString("SyncMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        internal static string SyncMenuLower {
            get {
                return ResourceManager.GetString("SyncMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNC.
        /// </summary>
        internal static string SyncMenuUpper {
            get {
                return ResourceManager.GetString("SyncMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        internal static string TagsLower {
            get {
                return ResourceManager.GetString("TagsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGS.
        /// </summary>
        internal static string TagsUpper {
            get {
                return ResourceManager.GetString("TagsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        internal static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task details.
        /// </summary>
        internal static string TaskDetailsLower {
            get {
                return ResourceManager.GetString("TaskDetailsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK DETAILS.
        /// </summary>
        internal static string TaskDetailsUpper {
            get {
                return ResourceManager.GetString("TaskDetailsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string TaskLower {
            get {
                return ResourceManager.GetString("TaskLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        internal static string TaskPlural {
            get {
                return ResourceManager.GetString("TaskPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task is due.
        /// </summary>
        internal static string TaskReminderPrefix {
            get {
                return ResourceManager.GetString("TaskReminderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me before tasks are due.
        /// </summary>
        internal static string TaskRemindersSetting {
            get {
                return ResourceManager.GetString("TaskRemindersSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 minutes.
        /// </summary>
        internal static string TaskRemindersSetting1 {
            get {
                return ResourceManager.GetString("TaskRemindersSetting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        internal static string TaskRemindersSetting2 {
            get {
                return ResourceManager.GetString("TaskRemindersSetting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string TaskRemindersSetting3 {
            get {
                return ResourceManager.GetString("TaskRemindersSetting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        internal static string TaskRemindersSetting4 {
            get {
                return ResourceManager.GetString("TaskRemindersSetting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string TaskSingle {
            get {
                return ResourceManager.GetString("TaskSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK.
        /// </summary>
        internal static string TaskUpper {
            get {
                return ResourceManager.GetString("TaskUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string TimePlural {
            get {
                return ResourceManager.GetString("TimePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string TimeSingle {
            get {
                return ResourceManager.GetString("TimeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timezone on your Remember The Milk account does not match the timezone that your phone is set to. This may cause problems with due dates and reminders..
        /// </summary>
        internal static string TimezoneMismatchDialog {
            get {
                return ResourceManager.GetString("TimezoneMismatchDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone Mismatch.
        /// </summary>
        internal static string TimezoneMismatchDialogTitle {
            get {
                return ResourceManager.GetString("TimezoneMismatchDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string TitleLower {
            get {
                return ResourceManager.GetString("TitleLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        internal static string TitleUpper {
            get {
                return ResourceManager.GetString("TitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        internal static string TodayLower {
            get {
                return ResourceManager.GetString("TodayLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        internal static string TodayUpper {
            get {
                return ResourceManager.GetString("TodayUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        internal static string TomorrowLower {
            get {
                return ResourceManager.GetString("TomorrowLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOMORROW.
        /// </summary>
        internal static string TomorrowUpper {
            get {
                return ResourceManager.GetString("TomorrowUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        internal static string UnhandledCrashDialog {
            get {
                return ResourceManager.GetString("UnhandledCrashDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has just occurred. Would you like to send an email to report it?.
        /// </summary>
        internal static string UnhandledErrorDialog {
            get {
                return ResourceManager.GetString("UnhandledErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        internal static string UnhandledErrorDialogTitle {
            get {
                return ResourceManager.GetString("UnhandledErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman is up-to-date.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string WeekLower {
            get {
                return ResourceManager.GetString("WeekLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        internal static string WeekUpper {
            get {
                return ResourceManager.GetString("WeekUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        internal static string WelcomeLower {
            get {
                return ResourceManager.GetString("WelcomeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        internal static string WelcomeUpper {
            get {
                return ResourceManager.GetString("WelcomeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman is working offline.
        /// </summary>
        internal static string WorkingOffline {
            get {
                return ResourceManager.GetString("WorkingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string YesLower {
            get {
                return ResourceManager.GetString("YesLower", resourceCulture);
            }
        }
    }
}
